### ISSUE TITLE
No longer works with Thunderbird 115.

### ISSUE THREAD

**Issue by zelch** [astehlik/thunderbird-addon-subaddress-reply#4] opened 2023-08-18 05:51 UTC
Pretty much what it says in the subject.  I hit reply or reply to all, and it's as if the extension isn't even loaded.

**Comment by eeedelli** [comment] 2024-01-11 22:05
I'm running TB 115.6.1 (32-bit) and have found the same, having just installed this addon.  I notice that it didn't ask me for any additional permissions.  I tried closing then re-opening it and have tested it from a work Outlook account that isn't in the list of accounts in TB but no joy.

**Comment by stackcoder** [comment] 2024-07-23 08:34
I can confirm that the extension does not work with TB 115.12. The Extension seems to load, but does not adjust the from address.

**Comment by astehlik** [comment] 2024-07-30 20:18
Thank you for reporting the issue.

I'm currently running 115.13.0 and for me it seems to work fine.

Can you please check if you see any error messages in the dev console `Ctrl`+`Shift`+`j` ?

**Comment by stackcoder** [comment] 2024-08-02 10:04
I also received the update to version 115.13.0, and now it works for me - thank you!
Maybe this was a bug within TB and this issue can be closed.

**Comment by astehlik** [comment] 2024-08-05 14:45
Nice, thank you for testing and the feedback :smiley:

**Closed as completed by astehlik** 2024-08-05 14:45 UTC
